"""Database creations

Revision ID: 8675a8eef013
Revises: 
Create Date: 2023-10-03 00:06:54.377164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8675a8eef013'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('load_test_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('type_load_tool', sa.Enum('locust', 'yandex_tank', name='loadtools'), nullable=True),
    sa.Column('upload_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('test_time_start', sa.TIMESTAMP(), nullable=False),
    sa.Column('test_time_end', sa.TIMESTAMP(), nullable=False),
    sa.Column('successful_result_test', sa.Boolean(), nullable=True),
    sa.Column('calculated_test', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['load_test_describe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('load_test_result_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('upload_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('test_time_start', sa.TIMESTAMP(), nullable=False),
    sa.Column('test_time_end', sa.TIMESTAMP(), nullable=False),
    sa.Column('successful_result_test', sa.Boolean(), nullable=True),
    sa.Column('calculated_test', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['load_test_describe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('load_test_result_summary')
    op.drop_table('load_test_result')
    # ### end Alembic commands ###
